name: Pulumi Infrastructure Destroy
on:
  workflow_dispatch:  

env:
  DOTNET_VERSION: '7'           # set this to the dot net version to use

jobs:
  preview:
    name: Destroy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      - name: Azure login
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: pulumi/actions@v5
        with:
          command: destroy
          stack-name: dev # When using an individual account, only use stack-name.
          work-dir: EcommerceApi.Infra
          cloud-url: azblob://state
          github-token: ${{ secrets.SAML_GITHUB_TOKEN }}
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT}}   
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY}}  
          PULUMI_CONFIG_PASSPHRASE: "whatever"     
          GITHUB_TOKEN: ${{ secrets.SAML_GITHUB_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}   
          ARM_CLIENT_SECRET: ${{ secrets.SP_PASSWORD}}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          ARM_TENANT_ID: b41b72d0-4e9f-4c26-8a69-f949f367c91d