name: Pulumi Infrastructure Deploy
on:
  push:
    branches:
        - main
env:
  DOTNET_VERSION: '7'           # set this to the dot net version to use
  INFRA-DIR: EcommerceApi.Infra
  INFRA-TEST-DIR: EcommerceApi.InfraTests

jobs:
  build-and-test:
    name: Build and Test Infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: ${{ env.DOTNET_VERSION }}     
      - name: Install dependencies
        run: dotnet restore
        working-directory: ${{ env.INFRA-DIR}}
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ${{ env.INFRA-DIR}}
      - name: Test
        run: dotnet test --no-restore --verbosity normal      
        working-directory: ${{ env.INFRA-TEST-DIR}} 
  Deploy:
    name: Deploy Infra
    needs: [build-and-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      - name: Azure login
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: pulumi/actions@v5
        with:
          command: up
          stack-name: dev # When using an individual account, only use stack-name.
          work-dir: EcommerceApi.Infra
          cloud-url: azblob://state
          github-token: ${{ secrets.SAML_GITHUB_TOKEN }}
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT}}   
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY}}  
          PULUMI_CONFIG_PASSPHRASE: "whatever"     
          GITHUB_TOKEN: ${{ secrets.SAML_GITHUB_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}   
          ARM_CLIENT_SECRET: ${{ secrets.SP_PASSWORD}}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          ARM_TENANT_ID: b41b72d0-4e9f-4c26-8a69-f949f367c91d